export const studentData = [
  {
    studentName:"abimran23",
    frontImg:"/images/imranfront.png",
    backImg:"/images/imranback.jpg",
    resBackImg:"/images/imranbackphone.jpg",
    className:"imran",
    certificates:[
      {
        img:'/certificat/imrancertificate1.jpg'
      },
      {
        img:'/certificat/imrancertificate2.jpg'
      },
    ]
  },
  {
    studentName:"maogtay21",
    frontImg:"/images/oqtayfront.png",
    backImg:"/images/oqtayback.jpg",
    resBackImg:"/images/oqtaybackphone.jpg",
    className:"oqtay",
    certificates:[
      {
        img:'/certificat/oqtaycertificate1.jpg'
      },
      {
        img:'/certificat/oqtaycertificate2.jpg'
      },
      {
        img:'/certificat/oqtaycertificat3.jpg'
      },
      {
        img:'/certificat/oqtaycertificate4.jpg'
      },
      {
        img:'/certificat/oqtaycertificate12.jpg'
      },
      {
        img:'/certificat/oqtaycertificate13.jpg'
      },
      {
        img:'/certificat/oqtaycertificate5.jpg'
      },
      {
        img:'/certificat/oqtaycertificate6.jpg'
      },
      {
        img:'/certificat/oqtaycertificate7.jpg'
      },
      {
        img:'/certificat/oqtaycertificate8.jpg'
      },
      {
        img:'/certificat/oqtaycertificate9.jpg'
      },
      {
        img:'/certificat/oqtaycertificate10.jpg'
      },
      {
        img:'/certificat/oqtaycertificate11.jpg'
      },
    ]
  },
  {
    studentName:"khraul19",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"khfarkhan29",
    frontImg:"/images/farxanfront.png",
    backImg:"/images/imranback.jpg",
    resBackImg:"/images/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"mamurad05",
    frontImg:"/images/muradfront.png",
    backImg:"/images/imranback.jpg",
    resBackImg:"/images/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"alidris27",
    frontImg:"/images/idrisfront.png",
    backImg:"/images/idrisback.jpg",
    resBackImg:"/images/idrisbackphone.jpg",
    className:"alidris27"
  },
  {
    studentName:"azdavud06",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"rakabira07",
    frontImg:"/images/kabirafront.png",
    backImg:"/images/imranback.jpg",
    resBackImg:"/images/imranbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"rafarahnaz11",
    frontImg:"/images/farahnazfront.png",
    backImg:"/images/farahnazback.jpg",
    resBackImg:"/images/farahnazbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"ibfuad27",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"alayaz28",
    frontImg:"/images/ayazfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"maamir14",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"kaamina21",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"mafateh12",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"dodeniz12",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"almaryam04",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"alreyhana01",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"agali10",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"almuhammad20",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"kamehri28",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  // new
  {
    studentName:"alali13",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"asmurad11",  
    frontImg:"/images/asmurad11.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"maheydar15",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"asadelina19",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"betahir15",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"gurahim27",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"gusonam23",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"safuad30",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"sahuseyn17",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"avsarkhan16",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"shraul03",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"asharun30",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"vailhan08",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"asahmad02",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"shraul16",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  // new

  {
    studentName:"qafarid26",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"astamerlan08",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"haalif10",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },

  {
    studentName:"hakhadija13",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"jahasan09",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },
  {
    studentName:"jajafarsadig24",
    frontImg:"/images/raulfront.png",
    backImg:"/images/raulback.jpg",
    resBackImg:"/images/raulbackphone.jpg",
    className:"raul"
  },

]
